# Generated by Django 5.2.11 on 2026-03-01 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(choices=[('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('PARTNERSHIP', 'Partnership'), ('LIMITED_LIABILITY', 'Limited Liability Company'), ('PUBLIC_LIMITED', 'Public Limited Company')], max_length=50)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('tax_identification_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('nature_of_business', models.CharField(max_length=255)),
                ('date_incorporated', models.DateField()),
                ('business_commencement_date', models.DateField(blank=True, null=True)),
                ('cac_certificate', models.FileField(blank=True, null=True, upload_to='documents/cac/')),
                ('scuml_certificate', models.FileField(blank=True, null=True, upload_to='documents/scuml/')),
                ('tin_certificate', models.FileField(blank=True, null=True, upload_to='documents/tin/')),
                ('utility_bill', models.FileField(blank=True, null=True, upload_to='documents/utility/')),
                ('memart', models.FileField(blank=True, null=True, upload_to='documents/memart/')),
                ('board_resolution', models.FileField(blank=True, null=True, upload_to='documents/board/')),
                ('npsb_business_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_corporates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corporate',
                'verbose_name_plural': 'Corporates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='NIGERIAN', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('bvn', models.CharField(max_length=11, verbose_name='BVN')),
                ('nin', models.CharField(blank=True, max_length=11, null=True, verbose_name='NIN')),
                ('identification_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('DRIVERS_LICENSE', "Driver's License"), ('INTERNATIONAL_PASSPORT', 'International Passport'), ('VOTERS_CARD', "Voter's Card")], max_length=30)),
                ('next_of_kin_name', models.CharField(max_length=200)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('customer_type', models.CharField(choices=[('DIRECTOR', 'Director'), ('SIGNATORY', 'Signatory'), ('SHAREHOLDER', 'Shareholder')], default='DIRECTOR', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('pep', models.BooleanField(default=False, verbose_name='Politically Exposed Person')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='directors/photos/')),
                ('id_card_front', models.FileField(blank=True, null=True, upload_to='directors/id_front/')),
                ('id_card_back', models.FileField(blank=True, null=True, upload_to='directors/id_back/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='directors/signatures/')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='directors/address/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='corporates.corporate')),
            ],
            options={
                'ordering': ['-is_primary', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ledger_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tier', models.CharField(blank=True, max_length=20, null=True)),
                ('maximum_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('maximum_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('freeze_status', models.CharField(blank=True, max_length=20, null=True)),
                ('lien_status', models.CharField(blank=True, max_length=20, null=True)),
                ('pnd_status', models.CharField(blank=True, max_length=20, null=True)),
                ('npsb_order_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='corporates.corporate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('narration', models.CharField(max_length=255)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_account', models.CharField(blank=True, max_length=20, null=True)),
                ('beneficiary_bank', models.CharField(blank=True, max_length=10, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('response_code', models.CharField(blank=True, max_length=10, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='corporates.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
