# Generated by Django 5.2.11 on 2026-03-01 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='wallet',
            name='npsb_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('CORPORATE', 'Corporate'), ('INDIVIDUAL', 'Individual')], default='CORPORATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='corporates.corporate'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(default='NIGERIAN', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('bvn', models.CharField(max_length=11, unique=True, verbose_name='BVN')),
                ('nin', models.CharField(blank=True, max_length=11, null=True, verbose_name='NIN')),
                ('identification_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('DRIVERS_LICENSE', "Driver's License"), ('INTERNATIONAL_PASSPORT', 'International Passport'), ('VOTERS_CARD', "Voter's Card")], max_length=30)),
                ('next_of_kin_name', models.CharField(max_length=200)),
                ('next_of_kin_phone', models.CharField(max_length=20)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='customers/photos/')),
                ('id_card_front', models.FileField(blank=True, null=True, upload_to='customers/id_front/')),
                ('id_card_back', models.FileField(blank=True, null=True, upload_to='customers/id_back/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='customers/signatures/')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='customers/address/')),
                ('bvn_verified', models.BooleanField(default=False)),
                ('nin_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='corporates.customer'),
        ),
    ]
