# Generated by Django 5.2.11 on 2026-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporates', '0002_remove_wallet_customer_id_wallet_npsb_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='cac_status_report',
            field=models.FileField(blank=True, null=True, upload_to='documents/cac_status/'),
        ),
        migrations.AddField(
            model_name='corporate',
            name='company_reg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='contact_person_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='contact_person_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='industrial_sector',
            field=models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('FINANCE', 'Finance'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('RETAIL', 'Retail'), ('MANUFACTURING', 'Manufacturing'), ('AGRICULTURE', 'Agriculture'), ('REAL_ESTATE', 'Real Estate'), ('TRANSPORTATION', 'Transportation'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
        migrations.AddField(
            model_name='corporate',
            name='npsb_account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='npsb_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='npsb_submission_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='corporate',
            name='proof_of_address',
            field=models.FileField(blank=True, null=True, upload_to='documents/address/'),
        ),
        migrations.AddField(
            model_name='corporate',
            name='regulatory_license_fintech',
            field=models.FileField(blank=True, null=True, upload_to='documents/fintech_license/'),
        ),
        migrations.AddField(
            model_name='director',
            name='npsb_declined_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='npsb_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='other_nationality_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='business_type',
            field=models.CharField(choices=[('SOLE_PROPRIETORSHIP', 'Sole Proprietorship'), ('PARTNERSHIP', 'Partnership'), ('LIMITED_LIABILITY_COMPANY', 'Limited Liability Company'), ('CORPORATIONS', 'Corporation'), ('NGO', 'NGO'), ('COOPERATIVE', 'Cooperative'), ('SOCIAL_ENTERPRISE', 'Social Enterprise'), ('FRANCHISE', 'Franchise'), ('OTHERS', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='director',
            name='nationality',
            field=models.CharField(choices=[('NIGERIAN', 'Nigerian'), ('OTHER', 'Other')], default='NIGERIAN', max_length=50),
        ),
        migrations.AlterField(
            model_name='director',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
