server {
    listen 80;
    server_name sitanetmerchant.sitanetorbit.com 134.122.89.113;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /var/www/sitanetmerchant/staticfiles/;
    }

    location /media/ {
        alias /var/www/sitanetmerchant/media/;
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 300s;
        proxy_read_timeout 300s;
    }

    client_max_body_size 10M;
}
